name: voco_case
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.1
  build_runner: ^2.0.3
  flutter_riverpod: ^0.14.0+3
  material_dialogs: ^1.1.4
  shared_preferences: ^2.0.17
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - 'assets/images/'
  fonts:
    - family: 'lato'
      fonts:
        - asset: 'assets/fonts/Lato-Regular.ttf'

    - family: 'metal'
      fonts:
        - asset: 'assets/fonts/MetalMania-Regular.ttf'

    - family: Red Hat Display
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/RedHatDisplay-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/RedHatDisplay-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 600
        - asset: assets/fonts/RedHatDisplay-MediumItalic.ttf
          style: italic
          weight: 600
